name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: windows-latest
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: list directiories
        run: dir
      - name: Install frontend dependencies
        run: npm install --prefix frontend
      # Frontend lint, test, build
      - name: Check frontend style
        run: npm run lint --prefix frontend
      - name: Run frontend tests
        run: npm run test --prefix frontend
      - name: Build frontend
        run: npm run build --prefix frontend
      - name: install backend dependencies
        run: npm install --prefix backend
  tag_release:
    needs: [simple_deployment_pipeline]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(join(github.event.commits.*.message), '#skip')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@8c8163ef62cf9c4677c8e800f36270af27930f42
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch